apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        beta.kubernetes.io/instance-type: t2.micro
      containers:
      - name: mongo
        image: mongo
        ports:
        - containerPort: 27017
        resources:
            limits:
              cpu: 400m
              memory: 400M
            requests:
              cpu: 100m
              memory: 100M


